server:
  port: 3001
spring:
  datasource:
    url: jdbc:mariadb://silver-moon.co.kr:10800/HOMEPAGE
    driver-class-name: org.mariadb.jdbc.Driver
    username: lune6669
    password: !Mjh882505
    hikari:
      auto-commit: false
      connection-test-query: select 1
  jpa:
    properties:
      hibernate:
        format_sql: true
        hbm2ddl.auto: update
        implicit_naming_strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
        physical_naming_strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
    open-in-view: false
    show-sql: true

    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true
  session:
    redis:
      namespace: "moon_log"
    timeout: 60m
    store-type: none
  messages:
    basename: messages.validate_message
  http:
    encoding: utf-8
jwt:
  header: Authorization
  secret: bW9vbmxvZ+ulvOywvuyVhOyjvOyLoOyXrOufrOu2hOuTpOqwkOyCrO2VqeuLiOuLpC7snbTruJTroZzqt7jripTsoJzqsIDtj6ztirjtj7TrpqzsmKTroZzsk7jsmIjsoJXsnoXri4jri6Qu7J6Y67aA7YOB65Oc66as6rKg7Iq164uI64uk7KGw6riI66eM642U6ri46rKM7ZW067O86rmM7JqU
  token-validity-in-seconds: 86400
logging:
  level:
    org.hibernate.sql: debug
    org.hibernate.type: trace