server:
  port: 8080
  servlet:
    context-path: /
  tomcat:
    uri-encoding: UTF-8
    max-threads: 500
    min-spare-threads: 50
    max-connections: 5000
    accept-count: 3000
    max-http-header-size: 65536
    max-swallow-size: -1
    max-post-size: -1
    max-file-size: -1
    max-request-size: -1
    accesslog:
      enabled: true
      directory: logs
      prefix: localhost_access_log
      suffix: .txt
      file-date-format: .yyyy-MM-dd
      rotate: true
      pattern: "%h %l %u %t &quot;%r&quot; %s %b %D"
      buffered: true
      encoding: UTF-8
      conditionIf: time-taken > 0
      conditionUnless: response.status < 400
      condition: request.remoteHost != '
spring:
  datasource:
    url: jdbc:mariadb://silver-moon.co.kr:10800/HOMEPAGE
    driver-class-name: org.mariadb.jdbc.Driver
    username: lune6669
    password: '!Mjh882505'
    hikari:
      auto-commit: false
      connection-test-query: select 1
  jpa:
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: none
      format_sql: true
      hbm2ddl.auto: update
      dialect: org.hibernate.dialect.MariaDBDialect #마리아db를 기준으로 작성함을 명시하는 방언
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true
        implicit_naming_strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
        physical_naming_strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
  session:
    redis:
      namespace: "moon_log"
    timeout: 60m
    store-type: none
  messages:
    basename: messages.validate_message
  http:
    encoding: utf-8
jwt:
  header: Authorization
  secret: bW9vbmxvZ+ulvOywvuyVhOyjvOyLoOyXrOufrOu2hOuTpOqwkOyCrO2VqeuLiOuLpC7snbTruJTroZzqt7jripTsoJzqsIDtj6ztirjtj7TrpqzsmKTroZzsk7jsmIjsoJXsnoXri4jri6Qu7J6Y67aA7YOB65Oc66as6rKg7Iq164uI64uk7KGw6riI66eM642U6ri46rKM7ZW067O86rmM7JqU
  token-validity-in-seconds: 86400
logging:
  level:
    org.hibernate.sql: debug
    org.hibernate.type: trace