// @ts-ignore
export default function CategoryPage(params){
    console.log(params.category);
    return (
        <div>
            <h1>여긴 컨텐츠가 들어올겁니다. &nbsp asds
            sadsd
            asdas
            dasd
                as
                d
                asdwwwwwwwwwwwwwwwwwww
                wwwwwww
                as
                d
                asdwwwwwwwwwwwwwwwwwww
                wwwwwww
                as
                d
                asdwwwwwwwwwwwwwwwwwww
                wwwwwww
                as
                d
                asdwwwwwwwwwwwwwwwwwww
                wwwwwww
                as
                d
                asdwwwwwwwwwwwwwwwwwww
                wwwwwww
                as
                d
                asdwwwwwwwwwwwwwwwwwww
                wwwwwww
                as
                d
                asdwwwwwwwwwwwwwwwwwww
                wwwwwww
                as
                d
                asdwwwwwwwwwwwwwwwwwww
                wwwwwww
                as
                d
                asdwwwwwwwwwwwwwwwwwww
                wwwwwww
                as
                d
                asdwwwwwwwwwwwwwwwwwww
                wwwwwww
                as
                d
                asdwwwwwwwwwwwwwwwwwww
                wwwwwww
                as
                d
                asdwwwwwwwwwwwwwwwwwww
                wwwwwww
                as
                d
                asdwwwwwwwwwwwwwwwwwww
                wwwwwww
                as
                d
                asdwwwwwwwwwwwwwwwwwww
                wwwwwww
                as
                d
                asdwwwwwwwwwwwwwwwwwww
                wwwwwww
                as
                d
                asdwwwwwwwwwwwwwwwwwww
                wwwwwww
                as
                d
                asdwwwwwwwwwwwwwwwwwww
                wwwwwww
                as
                d
                asdwwwwwwwwwwwwwwwwwww
                wwwwwww
                as
                d
                asdwwwwwwwwwwwwwwwwwww
                wwwwwww
                as
                d
                asdwwwwwwwwwwwwwwwwwww
                wwwwwww
                as
                d
                asdwwwwwwwwwwwwwwwwwww
                wwwwwww
                as
                d
                asdwwwwwwwwwwwwwwwwwww
                wwwwwww
                as
                d
                asdwwwwwwwwwwwwwwwwwww
                wwwwwww
                as
                d
                asdwwwwwwwwwwwwwwwwwww
                wwwwwww


                as
                d
                asdwwwwwwwwwwwwwwwwwww
                wwwwwww
                as
                d
                asdwwwwwwwwwwwwwwwwwww
                wwwwwww
                as
                d
                asdwwwwwwwwwwwwwwwwwww
                wwwwwww
                as
                d
                asdwwwwwwwwwwwwwwwwwww
                wwwwwww
                as
                d
                asdwwwwwwwwwwwwwwwwwww
                wwwwwww
                as
                d
                asdwwwwwwwwwwwwwwwwwww
                wwwwwww
                as
                d
                asdwwwwwwwwwwwwwwwwwww
                wwwwwww
                as
                d
                asdwwwwwwwwwwwwwwwwwww
                wwwwwww
                as
                d
                asdwwwwwwwwwwwwwwwwwww
                wwwwwww
                as
                d
                asdwwwwwwwwwwwwwwwwwww
                wwwwwww
                as
                d
                asdwwwwwwwwwwwwwwwwwww
                wwwwwww
                as
                d
                asdwwwwwwwwwwwwwwwwwww
                wwwwwww
                as
                d
                asdwwwwwwwwwwwwwwwwwww
                wwwwwww
                as
                d
                asdwwwwwwwwwwwwwwwwwww
                wwwwwww
                as
                d
                asdwwwwwwwwwwwwwwwwwww
                wwwwwww</h1>
        </div>)
}